### ISSUE TITLE
Not an editor command: UpdateRemotePlugins

### ISSUE THREAD

**Issue by vnovichek** [stevearc/gkeep.nvim#5]
**Describe the bug**
UpdateRemotePlugins is absent.

**Version information**
 - OS: macOS 12.1
 - Neovim: 
```
NVIM v0.6.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@BigSur

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.6.0/share/nvim"
```
 - Gkeep: 
```
  gkeep: health#gkeep#check
  ========================================================================
  ## gkeep
  │ - OK: gkeepapi 0.13.7 installed
  │ - OK: keyring installed
  │ - ERROR: Remote plugin not found
  │   - ADVICE:
  │   │ - Try running :UpdateRemotePlugins and restart
```

**Comment by stevearc** [comment]
Well that's interesting since `UpdateRemotePlugins` is a built-in command (see `:help UpdateRemotePlugins`). A quick google around suggested that possibly the internal script hasn't been loaded yet for you. I'm not sure how this could happen, but try
```
:runtime! plugin/rplugin.vim
:UpdateRemotePlugins
```

You may also need to set `let g:loaded_remote_plugins = 0` before. For further diagnosis, the command should be defined in [rplugin.vim](https://github.com/neovim/neovim/blob/1dcdf86849d58d6ff5c2ca6728657e7305226a36/runtime/plugin/rplugin.vim#L63). If you run `:scriptnames`, you should see that file in there somewhere (for me it shows up as ` 60: /tmp/.mount_nvimk4sNN2/usr/share/nvim/runtime/plugin/rplugin.vim`)

**Comment by vnovichek** [comment]
Thanks a lot, my bad, deep down in my lua configs there was a line: vim.g.loaded_remote_plugins = 1. Commenting it out helped.
